### ISSUE TITLE
Suggestion: Would it be possible to add the option "Minimize to tray"

### ISSUE THREAD

**Issue by pqsmmobile** [ledoge/novideo_srgb#16]

**Comment by ledoge** [comment]
Just curious – what is your use case that you're frequently turning it on and off? I figured that since, unlike dwm_lut, this tool works with everything and doesn't really have any downsides, that this wouldn't be needed. (unless you're frequently switching to and from applications that do their own color management, I guess).

**Comment by pqsmmobile** [comment]
> Just curious – what is your use case that you're frequently turning it on and off? I figured that since, unlike dwm_lut, this tool works with everything and doesn't really have any downsides, that this wouldn't be needed. (unless you're frequently switching to and from applications that do their own color management, I guess).

**Comment by pqsmmobile** [comment]
There is a conflict with madVR and the color profile/lut gets applied again resulting a much darker picture.

**Comment by ledoge** [comment]
I see – I'll look into adding the ability to minimize to tray when I have time, but no promises.

**Comment by aufkrawall** [comment]
> There is a conflict with madVR(with its own 3dlut) and the color profile/lut gets applied again resulting a much darker picture.

You could re-run calibration with novideo_srgb clamp active and create 3D LUTs from it, or you could set calibration settings in madVR to "already calibrated" and select the correct gamma setting there (seems to be relevant only for HDR tonemapping, pure power curve should be correct).

**Comment by ledoge** [comment]
Should be fixed with the latest release, as you can easily toggle the clamp from the tray context menu now.
