### ISSUE TITLE
To Calibrate, or not to Calibrate... and more Questions.

### ISSUE THREAD

**Issue by James-F2** [ledoge/novideo_srgb#19]
Reading ledoge's reply from another thread, which I'll quote here:

> Calibrating just adds vcgt data to the profile (which might result in a more accurate profile?), but novideo_srgb works perfectly fine with or without vcgt data. It's not relevant for the calculation of the black point.

I'm still not sure whether "Tone Curve" Calibration is needed at all, or skipping Calibration by selecting "As Measured" will produce just as accurate gamma tracking with Profiling only.
The big factor for this decision is measurement **time**, by skipping calibration I save a lot of time.

Questions;
1. Is Profiling only provides enough data for "calibrate gamma to" option in novideo_srgb to generate an accurate gamma curve?
2. If so, will more grey/neutral patches in the Testchart produce more data points for the LUT math to work with hence producing more accurate results with less interpolation?
3. What Profile Type will produce the best results for color and gamma tracking?

Thank you.

**Comment by ledoge** [comment]
>Is Profiling only provides enough data for "calibrate gamma to" option in novideo_srgb to generate an accurate gamma curve?

Yes.

>If so, will more grey/neutral patches in the Testchart produce more data points for the LUT math to work with hence producing more accurate results with less interpolation?

Absolutely!

>What Profile Type will produce the best results for color and gamma tracking?

That's something I'm not entirely sure about myself, as it probably depends on the exact optimization algorithms that ArgyllCMS uses for the various profile types. Theoretically speaking, I would expect a 3 curves + matrix profile generated by ArgyllCMS to provide better results than an XYZ LUT profile, as novideo_srgb has to derive the tone response curves and PCS matrix from an XYZ LUT profile anyway. It does this in a fairly primitive way, and I assume the algorithm used by ArgyllCMS would perform slightly better. But as long as a display is reasonably well-behaved, I would expect them to perform about the same in practice (and if it's not, then a calibration with novideo_srgb can't produce good results anyway).

**Comment by James-F2** [comment]
Thank you.

I have noticed that clamping remains enabled after restart, are the settings saved somewhere in the registry or in the gpu driver?

**Comment by ledoge** [comment]
IIRC everything except the gamma LUTs is stored in one registry key, and I'm not sure if those LUTs are also in the registry or somewhere else.
