### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by James-F2** [ledoge/novideo_srgb#20]
Multidimensional icon in the zip, looks great.

[CIE Icon.zip](https://github.com/ledoge/novideo_srgb/files/8213541/CIE.Icon.zip)

![CIE icon 256](https://user-images.githubusercontent.com/31185814/157393148-d942dc9f-0327-4196-a9cd-02e654e8432c.png)

**Comment by ledoge** [comment]
Thanks! I didn't want to use that exact file because of copyright/licensing, but this gave me the idea to just use the CIE 1931 xy sRGB triangle as the icon. Made my own version of that and just pushed a release with it.
