### ISSUE TITLE
Outline and shadow of the mouse cursor fade away while clamp is enabled.

### ISSUE THREAD

**Issue by demonqiqi** [ledoge/novideo_srgb#30]
Mouse cursor especially the finger pointer doesn‘t look sharp.

**Comment by Tallulah88** [comment]
That's weird. You can open the Windows performance options, check "Adjust for best appearance", apply and see if it helps. This has to do with enabling the mouse pointer shadow.
![pointer shadow](https://user-images.githubusercontent.com/104866331/171170637-38ca9fad-79c8-4ae1-be34-ddd1354cb0c3.png)

If it's not related, then maybe is just that the new gamma curve is making your pointer shadow less dark and you are not used to it. On Windows there's no desktop color management, so you probably should use sRGB or 2.2 gamma curve for a "correct" visualization of the desktop. Search for test images or run a verification to confirm if your gamma settings are correct. It could be related to a profile.

**Comment by ledoge** [comment]
Probably the same issue as #24. For whatever reason, the cursor overlay doesn't interact nicely with the color space conversion. AFAIK the only way to work around this is by forcing software rendering of the cursor using a program like [this](https://www.monitortests.com/forum/Thread-SoftCursor).

**Comment by ledoge** [comment]
That workaround is mentioned in the README now, but other than that I don't think there's anything I can do, unfortunately.
