### ISSUE TITLE
Clamping carries over to HDR mode

### ISSUE THREAD

**Issue by valentyn-l** [ledoge/novideo_srgb#4]
The sRGB clamping of DCI-P3 colors carries over when enabling HDR, be it on the desktop or playing HDR games, which unintendedly reduces color depth and saturation.

**Comment by ledoge** [comment]
Can't do anything about that, unfortunately. Don't think the API lets you specify whether to apply it to SDR only or also to HDR. Alternatively, it might be possible to periodically check if HDR if active on a monitor and toggle the clamp accordingly. Not sure how much effort that would be to implement.

**Comment by valentyn-l** [comment]
Ah, I understand. Thank you! :)

I just wanted to also say that enabling HDR actually provides the correct colour space for non-HDR content on a DCI-P3 compliant display, but its current implementation in Windows (both 10 and 11) is buggy and unreliable. Sometimes when exiting HDR application such as games, the image becomes over-brightened and oversaturated for no reason, and on the flip-side when exiting SDR applications into an HDR environment, the image becomes too dark. 

I don't know if this is an Nvidia driver or Windows issue as I haven't had the chance to test with an AMD GPU, but I sure hope that it gets fixed some day.

**Comment by beefcat666** [comment]
Thought I would chime in and voice my support for implementing a fix for this, even if it is a bit hacky.

Windows has an event you can listen for that fires off whenever there is a change to the display settings. I assume that includes switching between sRGB and DCI-P3.

My monitor forcibly enables its variable backlighting feature when in HDR mode, so I prefer to only use it when viewing actual HDR content. This results in me switching fairly frequently.

**Comment by ledoge** [comment]
Should be fixed now with the v3.2 release.
