### ISSUE TITLE
Applies clamp when NV HDR is enabled

### ISSUE THREAD

**Issue by sargonuspa** [ledoge/novideo_srgb#41]
Glad that the clamp disables itself when HDR is enabled but it remains active when the application or game enables HDR automatically, for example Elden Ring, RE2/3 Remake and MPCBE with MadVR to name a few which use the NVapi for HDR.

**Comment by ledoge** [comment]
This should be fixed in v3.4, please try it and report back.

**Comment by sargonuspa** [comment]
Tested in MadVR and Elden Ring and all is good so far.  Thank you dude for a fantastic application.

**Comment by sargonuspa** [comment]
I just noticed that it still clamps when I viewed a Youtube video on MPCBE with madvr and saw that colours were slightly different from Youtube using my displays internal app.  Checked my displays colour management system when playing that HDR video with clamp enabled and it flagged up as bt709.  When clamp is disabled, it flags up as bt2020.
