### ISSUE TITLE
Closes when PC wakes up

### ISSUE THREAD

**Issue by sargonuspa** [ledoge/novideo_srgb#43]
When I wake PC from hibernate, sign in, and the system starts up, I noticed that the application closes though the clamp is still enabled.

**Comment by ledoge** [comment]
Can confirm, it crashes when trying to get the HDR status for a display right after waking up. Will try to figure out a workaround.

**Comment by sargonuspa** [comment]
It also closes when I turn on my display.

**Comment by ledoge** [comment]
"Fixed" for now since I went back to just checking for Windows HDR due to the issues with NVAPI HDR.
