### ISSUE TITLE
Intel Graphics Support?

### ISSUE THREAD

**Issue by GK6475** [ledoge/novideo_srgb#44]
My laptop uses Intel Graphics for the laptop display, instead of the Nvidia GPU. As a result, I cannot do any sRGB clamping using novideo_srgb. Can you please add support for Intel adapters?

**Comment by ledoge** [comment]
Right now I have no need for that myself so it's very unlikely I'll spend the required time into it, but for anyone who wants to look into it, this should be possible with these recently released APIs: https://github.com/intel/drivers.gpu.control-library/blob/3a26d0b3e9f3189bf68f4c1d6fc188dd9e08c088/Samples/Color_Samples/Color_Sample_App.cpp

**Comment by GK6475** [comment]
Thanks, I'll try it.

**Comment by GK6475** [comment]
Also, how do I run this for a specific color profile? Does the program have a GUI?
