### ISSUE TITLE
Is the processing in 16bit?

### ISSUE THREAD

**Issue by James-F2** [ledoge/novideo_srgb#6]
I'm seeing banding in the dark region when enabling gamut clamping.
I'm wondering whether the internal GPU process is in 16bit before it outputs 8bit to display?

Attached ICC from EDID and 16bit grey ramp test pattern.
[16Bit Gradient.zip](https://github.com/ledoge/novideo_srgb/files/7189687/16Bit.Gradient.zip)
[Gigabyte M32Q.zip](https://github.com/ledoge/novideo_srgb/files/7189689/Gigabyte.M32Q.zip)

Disabled:
*Left most shade is 0,0,0 black, pattern zoomed 500%, camera overexposed, IPS glow.
![Disabled](https://user-images.githubusercontent.com/31185814/133884546-6e6e43bf-b01d-4e91-aade-027b09674f05.jpg)

Enabled 1:
![Enabled 1](https://user-images.githubusercontent.com/31185814/133884551-cca89590-7f56-4607-abb7-9bffdd892386.jpg)

Enabled 2:
![Enabled 2](https://user-images.githubusercontent.com/31185814/133884559-18910da2-c994-4329-9287-d77ab7d4ebd7.jpg)

**Comment by ledoge** [comment]
No idea, sorry. The only public information about this stuff that I could find is [here](https://on-demand.gputechconf.com/gtc/2017/presentation/s7394-tom-true-programming-for-high-dynamic-range.pdf) (slides 40 - 42), but it doesn't say anything about the precision.

**Comment by aufkrawall** [comment]
Internal precision seems to be sufficient, but you need to manually enable dithering with Nvidia and 8 bit output (enabled by default for 10 bit output and AMD also 8 bit output).
CalibrationTools offers it to do it via UI by calling NVAPI:
https://bitbucket.org/CalibrationTools/calibration-tools/downloads/

@ledoge At this occasion: The 1D LUT calibration part probably is out of scope for this project, right? CalibrationTools is a great program, though unfortunately Windows still seems to break color precision of it after system suspend etc.

**Comment by ValZapod** [comment]
On AVSfoum I read that nvidia dither is a little buggy in a sense that it worse for higher luminance stuff or whatever. Where it works by default, like limited RGB.
