### ISSUE TITLE
YouTube progress bar shadow opacity reduced significantly on Chromium browsers

### ISSUE THREAD

**Issue by softsoundd** [ledoge/novideo_srgb#73]
When enabling the clamp on my primary display, the shadow behind the YouTube progress bar and its associated UI dissapears almost completely, making the seconds/heatmap/buttons quite hard to discern - especially amongst bright content. 

This behaviour goes away when:

- disabling the clamp on my primary display
- switching to another tab and switching back to the tab with YouTube, however, as soon as the cursor leaves the browser tool bar and enters the page area, the issue is reintroduced
- moving the browser to my secondary display (with and without the clamp enabled on it)
- disabling browser hardware acceleration
- using non-Chromium browsers

I would take a screenshot/video of this behaviour, but both OBS and snipping tool do not show this behaviour, so I can only provide photos of the display:

Clamp enabled:
![image](https://github.com/ledoge/novideo_srgb/assets/90562023/59ae9a62-650f-40a6-b763-eaee9bb3eb5a)

Clamp disabled:
![image](https://github.com/ledoge/novideo_srgb/assets/90562023/7a69f862-6c14-4479-8fdd-4e2e5fd1cb2e)

**Comment by ledoge** [comment]
I can't reproduce it on my machine, but this reminds me of the cursor issue described with the README, so it seems like another case of the GPU not doing compositing properly when the color space transform pipeline is active? Only potential fix I can think of is to [disable MPO](https://nvidia.custhelp.com/app/answers/detail/a_id/5157).

**Comment by softsoundd** [comment]
Just an update to this - setting the ANGLE graphics backend to OpenGL in the browser's experimental flags resolved the above issue, although this may not be ideal for all applications.

**Comment by softsoundd** [comment]
> Just an update to this - setting the ANGLE graphics backend to OpenGL in the browser's experimental flags resolved the above issue, although this may not be ideal for all applications.

Update again. This workaround is no longer needed, 24H2 has fixed the issue.
