### ISSUE TITLE
Is it possible to edit the edid of the monitor so built in srgb clamp works correctly.

### ISSUE THREAD

**Issue by mrysrname** [ledoge/novideo_srgb#8]
Srgb mode of my monitor clamp the colors too much. Is it possible to edit the monitor's edid in a way that i can tune how built in srgb clamp work or SDR calibration in Windows HDR mode work ? Both looks identically dull (srgb clamp in SDR, SDR image in HDR). My monitor is gsync ultimate so it has SDR calibration in HDR mode but both this calibration and the srgb mode overshoots and clamps more than it should.

**Comment by pasi123567** [comment]
So if this setting is added of editing the values manually we could theoretically clamp the colors to any colorspace (incl. custom space) that is in the means of the gammut of the monitor right? If the monitor can reproduce Rec2020 for example we could clamp it to AdobeRGB, DCI-P3 or sRGB correct? If thats the case this would be a gamechanger for deciding which monitor to get.

**Comment by ValZapod** [comment]
> added of editing the values manually we could theoretically clamp the colors

No, this works without editing it.

> If the monitor can reproduce Rec2020 for example we could clamp it to AdobeRGB, DCI-P3 or sRGB correct?

If it support SDR 2020 then sure. But most are BT.2100, HDR.

**Comment by ValZapod** [comment]
> . Is it possible to edit the monitor's edid in a way

You need a spectrometer for that.

**Comment by ledoge** [comment]
Old issue, but this has been supported for a long time now via the use of ICC profiles. If you really want to use custom coordinates instead of using an existing ICC profile, you can use DisplayCAL to create a synthetic ICC profile with the exact coordinates you want.
