### ISSUE TITLE
L* tone curve option

### ISSUE THREAD

**Issue by DioVila** [ledoge/novideo_srgb#81]
Firstly, I'd like to express my gratitude for the creation of such a fantastic application. Thank you for all the hard work you've put into making it what it is today.

I'm reaching out because I have a suggestion for an enhancement. However, I'm not entirely sure if this is the appropriate place to share it.

The suggestion pertains to the addition of an _"L* tone curve"_ to the **"Calibrate gamma to:"** options. I've noticed that DisplayCal allows calibration to an L* tone curve, and I believe it would be valuable to include this option in the list of available tone curves.

**Comment by ledoge** [comment]
Just added it, please test it and let me know if it works as expected :)

**Comment by DioVila** [comment]
I wanted to extend my gratitude for swiftly incorporating the "L* Tone Curve" option - it's truly remarkable!

I've had the chance to test it out, and it works like a charm. I believe this feature will be useful, especially in contexts where uniformity and perceptual consistency take precedence. Your responsiveness in implementing this enhancement is greatly appreciated.

Thank you once again for your efforts in enhancing the application's functionality :)
