### ISSUE TITLE
Unable to load ICC profile as target ( rTRC is not of curveType )

### ISSUE THREAD

**Issue by Galf506** [ledoge/novideo_srgb#94]
I've been back in the calibration hole and I wanted to give a shot to calibrating without clamp (I'm using Calibrite PROFILER as DisplayCAL doesn't work on W11 for me), then clamping after calibration. Using EDID primaries this yields a result near delta 4 which is unusable, I wanted to try using the ICC profile from my screen, but the application errors out with " rTRC is not of curveType ", pic related.

Software used: Calibrite PROFILER (both in icc v2 and icc v4 version)
Device: xrite i1 Display
novideo_srgb version: 4.2 (didn't work before either, it was a much older version, I updated to try and fix it)

OS Windows 11 Pro build 22631
Nvidia Driver version: 551.86

![image](https://github.com/ledoge/novideo_srgb/assets/136910709/a6bd528c-9710-40ce-a83c-3c7132533074)

**Comment by ledoge** [comment]
Can you upload the v2 profile? According to the ICC v2 specification, the TRC *must* be of `curveType`, whereas ICC v4 also allows `parametricCurveType` (which I didn't add support for).

**Comment by Galf506** [comment]
> Can you upload the v2 profile? According to the ICC v2 specification, the TRC _must_ be of `curveType`, whereas ICC v4 also allows `parametricCurveType` (which I didn't add support for).

Sure, this SHOULD be v2, as I can't see a way to make sure my last one was v2 or v4. I also uploaded the one I know is a v4 file
https://file.io/07Riw76FzQv8

By the way, the Displaycal ones still appear to not error out... so it could be something wacky with Calibrite. But I'm stuck with this :/

**Comment by ledoge** [comment]
Both of the files are ICC v4.3. You can check it yourself by going to File -> Profile Information in DisplayCAL and looking at the "ICC Version" field. I don't know anything about Calibrite's software, so I don't know if/how you can convince it to make an actual v2 profile.

What issues are you having with DisplayCAL? I'm not aware of any that would prevent it from working properly on W11, except for the one where "Logitech LampArray Service" takes control of the colorimeter unless you manually stop it.

**Comment by Galf506** [comment]
> Both of the files are ICC v4.3. You can check it yourself by going to File -> Profile Information in DisplayCAL and looking at the "ICC Version" field. I don't know anything about Calibrite's software, so I don't know if/how you can convince it to make an actual v2 profile.
> 
> What issues are you having with DisplayCAL? I'm not aware of any that would prevent it from working properly on W11, except for the one where "Logitech LampArray Service" takes control of the colorimeter unless you manually stop it.

The weirdest thing happened, I tried again and it works... I have no idea wtf happened. The software even defaults to v2. It's the usual magic, I spend an afternoon trying stuff and when I finally make the post, it self fixes itself. (though sadly I still can't calibrate without clamp, probably because of the Quantum Dot layer, but if I clamp after calibration my delta shoots through the roof)

My issue with Displaycal is that it won't read the calibration device, no matter how many times I try to reinstall the Argyll drivers
