### ISSUE TITLE
Would it be possible to create an sRGB setting with a 2.2 gamma curve?

### ISSUE THREAD

**Issue by cpod12** [ledoge/novideo_srgb#97]
I've looked a bit into the code and as far as I can tell it seems that it uses the sRGB piecewise curve for the sRGB/BT.709 setting, but think it would be nice if there was an option to use pure power 2.2 gamma too. It would be cool to add BT.1886 as well. Or is there a way to do this already with EDID and not using an ICC profile? If there isn't I'd be willing to look into adding those settings.

**Comment by Cpod12** [comment]
Oh, wait. It seems like that only applies to ICC profiles. That probably isn't possible then.

**Comment by cpod12** [comment]
I realized that only works with ICC profiles. Probably can't be added.
